### ISSUE TITLE
Feat: Adding transitions and hover effects for navbar and theme change button

### ISSUE THREAD

**Issue by Varad0014** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#101]
### Describe the feature

I can enhance the navbar by adding underline hover effects to the links and adjusting their vertical alignment for symmetry. Additionally, I can implement a smooth transition for the theme button when switching between light and dark modes, as the change is currently abrupt. If these improvements are relevant, please assign this issue to me.

### Add ScreenShots

Current navbar:

https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/77493105/613ba840-91ce-41cd-8384-86ebb09c1e1a

Hover effect which I can add:

https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/77493105/df021c24-4b41-469b-8d8d-af404f61d71d

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varad0014** [comment]
Hey @SiddharthBahuguna,
Please assign me this issue if you find this relevant.

**Comment by SiddharthBahuguna** [comment]
I think this task is not relevant enough. Please choose a task that is required for the improvement of the project.
