### ISSUE TITLE
Feat: add social media icons in footer 

### ISSUE THREAD

**Issue by jayanththalla** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#109]
### Describe the feature

add social media links to the footer 
please assign me @pa
### Add ScreenShots

![image](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/121346142/a7b165b1-45c1-41a9-ab1a-d2afba33362f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SiddharthBahuguna** [comment]
I think this task is not relevant enough. Please choose a task that is required for the improvement of the project.
