### ISSUE TITLE
Message Box Not Hiding Properly on Website

### ISSUE THREAD

**Issue by prudhvi-1618** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#12]

**Comment by SiddharthBahuguna** [comment]
Yes,you are assigned the task.

**Comment by prudhvi-1618** [comment]
Subject: Urgent: Issue Misdirected, Need Assistance

Hi ,

I'm reaching out regarding an issue that was inadvertently created in this
repository. It was meant for another repository, shrink. I apologize for
any confusion or inconvenience this may have caused.

Could you kindly assist in transferring the issue to the correct
repository? I understand if this may require some administrative action on
your end, and I appreciate your help in rectifying this mistake swiftly.
