### ISSUE TITLE
Add confimation message after signing in

### ISSUE THREAD

**Issue by ananyag309** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#137]
### What's wrong with the existing documentation

When we fill our details for sign it the form gets reset instead we can add something a alert message of confirmation before the form gets close

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anuragnegi000** [comment]
assign this issue to me

**Comment by nishant0708** [comment]
hey @SiddharthBahuguna  @anurag6569201  Can i work on this

**Comment by SiddharthBahuguna** [comment]
not required.
