### ISSUE TITLE
The signup data is not stored and hence the user is unable to sign in

### ISSUE THREAD

**Issue by samarsajad** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#148]
### Describe the feature

On signing in after sign up, "User does not exist" is displayed. The data entered during sign up must be stored so that it could be used while signing in

### Add ScreenShots

![image](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/142666229/d0c2c8b8-0092-4725-906f-bf91d710339e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by samarsajad** [comment]
Please assign this issue to me

**Comment by anurag6569201** [comment]
@samarsajad have you ever worked with sqlite bro.... have you ever worked with render. com ..... I am closing this because it's not an error it happens because of not any dedicated server for the database.
