### ISSUE TITLE
Feat: Adding Google auth 

### ISSUE THREAD

**Issue by mukilan2815** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#154]
### Describe the feature

We can add google auth for one click signin so that user can easily signin .

### Add ScreenShots

![image](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/71129858/945ff837-f1c2-447f-9ec3-9b2ecb59a57b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shubham-Zone** [comment]
@SiddharthBahuguna please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development
