### ISSUE TITLE
Feat: Add Preloader

### ISSUE THREAD

**Issue by AsmitaMishra24** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#158]
### Describe the feature

A preloader is an essential feature for enhancing user experience by indicating the progress of loading content. It helps in keeping the users engaged while the main content is being fetched or rendered. Implementing a preloader can significantly improve the perceived performance of our application.

### Add ScreenShots

My Previous Work:-
https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/146121869/890f2413-5d26-4a4e-886f-de974bc5a880

https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/146121869/0ee7c36f-94e1-46c9-a6d2-d79b2a8452ca

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SiddharthBahuguna** [comment]
i think it is already created
