### ISSUE TITLE
Adding forgot password option 

### ISSUE THREAD

**Issue by mahek0620** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#161]
### Describe the feature

Adding forgot password option in login page

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sohinirathor2004** [comment]
I want to work on this issue and I've gone through the Code of Conduct. I also agree to follow it. Here are some screen shots to accompany the feature request of adding the forgot password option to the login page. I'm happy to be part of GSSOC'24 and to contribute to this project. Please assign #161 issue to me.
