### ISSUE TITLE
improving about us page

### ISSUE THREAD

**Issue by mahek0620** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#162]
### What's wrong with the existing documentation

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mrunal1309** [comment]
@SiddharthBahuguna can you please assign me this issue ?

**Comment by SiddharthBahuguna** [comment]
it is not required
