### ISSUE TITLE
Feat:Dockerize the app

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#164]
### Describe the feature

As you write we need this python version and also need to make virtual environment but many user feel difficulty in doing this and also for running your app may be some user may have not that python version so we have to dockerize the app
1. it helps in making virtual environment according to your given configuration in one line
2. it is not depend in mac or windows it works in all operating system 
3. through one line command user can run your app easily

### Add ScreenShots

no screenshot

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anurag6569201** [comment]
@agarwalhimanshugaya dockerizing for such smaller applications not worth it and also not everyone well aware about devOps so instead of dockerizing that way is more preferable by the majority.

**Comment by agarwalhimanshugaya** [comment]
@anurag6569201 yes u r right i thought in expect of doing all these steps in docker we run app with one command so that i suggest
