### ISSUE TITLE
Add Icons

### ISSUE THREAD

**Issue by sailaja-adapa** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#165]
### Describe the feature

Hello Project Admin
I would like to add icons to Navbar so that it will Make our website to look attractive
Can you assign me this issue under GSSOC'24 @SiddharthBahuguna @anurag6569201 

### Add ScreenShots

![ii](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/161804629/95fc5fec-e393-457c-8aae-5562589fe8d5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anurag6569201** [comment]
@sailaja-adapa not required thanks
