### ISSUE TITLE
Add Rate Us Option

### ISSUE THREAD

**Issue by sailaja-adapa** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#166]
### Describe the feature

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a rate us option it will allow the user to rate our website and also he can suggest us to improve if any 
I will add Rate us Option on navbar

Can you please assign me this issue under gssoc'24 @anurag6569201 @SiddharthBahuguna 

### Add ScreenShots

![ii](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/161804629/4d65a22c-f150-4c9c-82e7-157628e918e6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aman0474** [comment]
I would like to work on this issue i have understood the problem statement and will provide the optimal solution for it
So can you assign it to me

**Comment by anurag6569201** [comment]
not required such feature @sailaja-adapa tqs
