### ISSUE TITLE
Feat: Disable the text selection on the website

### ISSUE THREAD

**Issue by nainika0305** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#169]
### Describe the feature

The text is getting selected on the website. It should be turned off as it unnecessary on the login page and decreases the UX. 

### Add ScreenShots

![image](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/149311472/a3769ff8-3661-4ecf-b866-b7e4b87ad3d2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SiddharthBahuguna** [comment]
not required @nainika0305
