### ISSUE TITLE
update read me file

### ISSUE THREAD

**Issue by Vipullakum007** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#17]
you can update readme file

**Comment by AbhishekSingh-22** [comment]
I would like to update the readme file for better understanding as a part of GSSOC'24. Please assign me this issue as well as label the issue.

**Comment by SiddharthBahuguna** [comment]
Already assigned

**Comment by samikshapandagle** [comment]
Hi please assign this issue to me and believe I can address it as part of the contributor of GSSoc.

**Comment by AbhishekSingh-22** [comment]
Please assign me this issue under GSSOC'24. I haven't be assigned this issue till now. I will make the following changes in the readme file


# NEWS-AGGREGATOR-PROJECT

# Overview ✳️

The news aggregator project aims to create a centralized platform that curates and organizes news articles and updates from various sources across the internet. It is being developed to address the growing need for a consolidated and user-friendly platform that offers reliable and diverse news content.

# Features 😱
- Centralized Platform: All your news sources in one place.
- Customizable: Choose the sources and topics you're interested in.
- User-Friendly Interface: Easy navigation and intuitive design.
- Reliable: Dependable news updates from reputable sources.
- Diverse Content: Access news articles from a wide range of sources.
# Prerequisites
- Python 3.x installed on your machine
- pip (Python package manager)





    
# Steps For Contribution⚡

0. Star ⭐

1. Fork 

2. Clone the forked repository.
```css
git clone https://github.com/<your-github-username>/NEWS-AGGREGATOR-PROJECT.git
```
  
3. Navigate to the project directory.
```py
cd NEWS-AGGREGATOR-PROJECT
```
4. Install virtualenv library
``` bash
pip install virtualenv
```
5. Create virtual environment
```bash
virtualenv venv
```

6. Activate virtual environment

- For Windows:
``` bash
venv\Scripts\activate
```

- For Unix/Linux/MacOS:
```bash
source venv/bin/activate
```

7. Install required dependencies
```bash
pip install -r requirements.txt
```

8. Create a new branch.
```bash
git checkout -b <your_branch_name>
```

9. Make changes.

10. Stage your changes and commit
```bash
git add -A

git commit -m "<your_commit_message>"
```

11. Push your local commits to the remote repo.
```bash
git push -u origin <your_branch_name>
```

12. Create a Pull Request.

13. Congratulations! 🎉 you've made your contribution.


## Screenshots 📷
Home Page
![Home Page](Screenshots/HomePage.png)

About Page
![About Page](Screenshots/AboutPage.png)


Also Please add labels for this issue as well.

**Comment by SiddharthBahuguna** [comment]
Approved.

**Comment by AbhishekSingh-22** [comment]
Please add a GSSOC'24 label as well as the corresponding level for this issue as If the label isn't found then the points won't be counted for the respective contributions. Please add the labels for each issue not only this one.

**Comment by AbhishekSingh-22** [comment]
Sorry to bother again @SiddharthBahuguna but the label should be as gssoc and level1, not as GSSOC'24 and Level-1. Could you please change this. Thank you.

**Comment by SiddharthBahuguna** [comment]
now check @AbhishekSingh-22

**Comment by AbhishekSingh-22** [comment]
> now check @AbhishekSingh-22

Thank you so much.

**Comment by SiddharthBahuguna** [comment]
You're welcome!
