### ISSUE TITLE
Add dedicated login/register page and Saving News functionality

### ISSUE THREAD

**Issue by Ishitva744** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#2]
As a contributor in GSSOC'24, I would like to add the following feature:

- Dedicated login/register page for the users
- Add new feature to allow users to **save** any news and **view** it later for future reference

**Comment by SiddharthBahuguna** [comment]
Yes, you can do that.

**Comment by Ishitva744** [comment]
May I also request you to label my issue accordingly.

**Comment by SiddharthBahuguna** [comment]
Ok

**Comment by AbhishekSingh-22** [comment]
I also like to work on this issue. Please assign this issue to me as a part of GSSOC '24
Also label the issue please.

**Comment by Ishitva744** [comment]
> As a contributor in GSSOC'24, I would like to add the following feature:
> 
> * Dedicated login/register page for the users
> * Add new feature to allow users to **save** any news and **view** it later for future reference

I have added the login/register page with full functionality and also the feature to save any news and view it later in a new url accessible from homepage. 

- Dedicated working login/register page.
https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/162673707/8df161f2-c3ea-4067-a22e-6523037910b3


- Feature for saving news and viewing it later accessible to only those who are logged in.
https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/162673707/1173a388-1200-4456-8a80-6acf0cb2ac9d

I have styled the login and register pages minimally but haven't styled the saved news page as I thought that whosoever will style the homepage will maintain that style in the other webpages. 

If there are any corrections needed, please let me know so that I can rectify them immediately. 
Also please label this issue under GSSoC'24 and the appropriate level.

**Comment by Deepthi-Ramineni** [comment]
I am very experienced in creating such pages. can you please assign this to me...???

**Comment by SiddharthBahuguna** [comment]
@Deepthi-Ramineni it is already created.
