### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#22]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by SiddharthBahuguna** [comment]
Sure!

**Comment by suhanipaliwal** [comment]
Please assign this issue to me so that I can start working on it. Also please add the labels of GSSOC'24 and a label of appropriate level like level 1, 2 or 3.

**Comment by SiddharthBahuguna** [comment]
Please send the link where label is needed to be assigned.
