### ISSUE TITLE
Improving the project structure, adding css and javascript to their own files

### ISSUE THREAD

**Issue by RajatAgrawal117** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#23]
### Describe the feature

I want to improve the overall Project Structure by organizing CSS and JavaScript files into their own dedicated directories within the static folder. By separating these files, we can enhance code maintainability and scalability. Can you please assign this issue to me under GSSOC'24?

### Add ScreenShots

![image](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/69640292/10ad02ea-1173-41c9-9a9a-033c3e8aa31b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SiddharthBahuguna** [comment]
Already assigned to another contributor

**Comment by RajatAgrawal117** [comment]
Is there any particular issue that you would like me to address or improve?

**Comment by SiddharthBahuguna** [comment]
I have assigned maximum issues to other contributers.You can suggest me any
issue which is not common among these.Than I can assign you.
