### ISSUE TITLE
Feat:Enhance Card Design for News Articles

### ISSUE THREAD

**Issue by RajatAgrawal117** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#24]
### Describe the feature

I propose enhancing the current design for displaying news articles on our website to provide a better user experience. First, I want to implement a responsive card layout using Bootstrap's grid system, ensuring the news cards adapt seamlessly to different screen sizes and devices.
Next, I aim to improve the card content by including a news image displayed at the top of the card, a title truncated with an ellipsis if too long, a brief description or excerpt of the article content, and buttons for copying the article URL, reporting inappropriate content, and sharing on social media platforms.
I also want to introduce interactive functionality. Clicking the news title should open the article content in a modal window instead of a new tab or window. The "Copy" button should copy the article URL to the clipboard. The "Report" button should open a modal with a form to submit a report for inappropriate or misleading content. Additionally, the social media share buttons (Instagram, WhatsApp, Facebook) should open the respective platform's share dialog with the article URL.
To enhance accessibility, I plan to add appropriate aria-label attributes to buttons for better screen reader accessibility and ensure proper color contrast between text and background for users with visual impairments.
Finally, I want to apply styling enhancements by utilizing Bootstrap's built-in styles and utilities for consistent typography, button styles, and other components. I will also apply custom CSS to enhance the visual appeal of the cards and buttons, such as hover effects, border-radius, and brand-specific colors for social media buttons.

Can you assign it to me?

### Add ScreenShots

![image](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/69640292/bd0558fe-cb7f-4dba-bdb4-76193efcb200)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SiddharthBahuguna** [comment]
Approved.

**Comment by RajatAgrawal117** [comment]
I have generated a pull request, kindly review it. Thanks!
