### ISSUE TITLE
Missing Code of Conduct File in Repository

### ISSUE THREAD

**Issue by anshgautam-github** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#3]
Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. A Code of Conduct serves as a guideline for expected behavior, ensuring that contributors and participants feel safe, respected, and valued within our community space.

Kindly assign me this issue, so i can work towards it under GSSOC 24

**Comment by SiddharthBahuguna** [comment]
You can create code of conduct one of your own and add it in the project.

**Comment by anshgautam-github** [comment]
so after creating it , do i have to create the PR directly?

**Comment by SiddharthBahuguna** [comment]
Yes, you can do that.

**Comment by Karthikreddy0165** [comment]
I can solve this issue, Can you assign me this

**Comment by SiddharthBahuguna** [comment]
@Karthikreddy0165 I have assigned you.Please start.

**Comment by Karthikreddy0165** [comment]
thanks

**Comment by officeneerajsaini** [comment]
@anshgautam-github close this pr .
