### ISSUE TITLE
Feat: Greeting messages !

### ISSUE THREAD

**Issue by akshaydubey05** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#36]
### Describe the feature

Whenever someone initiates an **Issue** or create **Pull Request**, a bold and impactful greeting message shall spring forth, commanding attention and setting the tone for productive collaboration!

### Add ScreenShots

![Screenshot 2024-05-14 120724](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/123586645/ee870629-0fe5-456c-8dd7-10059db04dbe)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by akshaydubey05** [comment]
Hi, i created this issue please assign this issue to me under GSSOC'24.

**Comment by SiddharthBahuguna** [comment]
Ok.But,explain in brief

**Comment by akshaydubey05** [comment]
- Okay, so as we know, in open source projects, people solve **issues** to add or enhance features, and finding issues and solving 

them enhances the project, so a new person who creates their first issue will be automatically greeted with this feature!

- And after solving the issue, when they create a **pull** **request**, they will again be thanked, which I think is a very cool feature.
