### ISSUE TITLE
Feat: Adding a Bookmark page 

### ISSUE THREAD

**Issue by rashiranjan22** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#47]
### Describe the feature

Adding a page for bookmarked news articles can provide users with a convenient way to access and manage the articles they find interesting or want to read later. It would enhance the user experience by allowing them to easily track and revisit their saved articles, improving engagement and retention on the news aggregator website.

Kindly assign this issue to me under GSSOC'24
Also please label it level 2 or level 3 , it would be a great help

### Add ScreenShots

Bookmark page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SiddharthBahuguna** [comment]
Assigned.
