### ISSUE TITLE
Add PR template

### ISSUE THREAD

**Issue by suhanipaliwal** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#48]
I would like to add a pull request template for this repository. I believe that having a standardized template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review and merge pull requests.

Could you please assign this issue to me under GSSOC'24.

**Comment by SiddharthBahuguna** [comment]
You can create it on your own and please send me the link to assign that
task.

**Comment by suhanipaliwal** [comment]
Please assign this issue to me and add the required labels for GSSOC'24.

**Comment by SiddharthBahuguna** [comment]
#48 and #55 both are assigned to you

**Comment by suhanipaliwal** [comment]
I have completed this task in #55 .You can merge this pull request.

**Comment by SiddharthBahuguna** [comment]
please send link as I'm using Gmail.

**Comment by suhanipaliwal** [comment]
https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/pull/55

**Comment by SiddharthBahuguna** [comment]
i have merged.
