### ISSUE TITLE
paginator at homepage

### ISSUE THREAD

**Issue by anurag6569201** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#57]
i wanted to add paginator on the hompage while having all the cards at one page i wanted to make it more user interactive by adding paginator using django paginator

![image](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/140162738/77ea3470-94b8-4e31-93dc-5be4dc181f80)

**Comment by SiddharthBahuguna** [comment]
You can start working on it.
