### ISSUE TITLE
Text colors in the footer

### ISSUE THREAD

**Issue by suma30** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#58]
![Screenshot 2024-05-20 133622](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/112741893/2e186d79-2dcc-48d0-9e7c-b3b9ac63415f)

It looks good if the text colors under Quick links and Legal stuff are alike but they are not, and I can fix this,
please can you assign me this issue under GSSOC'24
@SiddharthBahuguna

**Comment by SiddharthBahuguna** [comment]
Ok
