### ISSUE TITLE
Feat: Add Hover Effects on Cards

### ISSUE THREAD

**Issue by AkshitGarg24** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#60]
### Describe the feature

The cards on the website currently lack a hover effect, which makes the user experience less engaging. To improve the visual appeal and interactivity of the website, I will implement a scaling effect on the cards when they are hovered over, using CSS transitions. This will make the website more dynamic and visually appealing. Kindly label this issue and assign this issue to me.

### Add ScreenShots

![Hover_Effects](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/153659573/7915c19d-1fba-4021-83a9-154954e41a5c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SiddharthBahuguna** [comment]
You can start working on it.

**Comment by AkshitGarg24** [comment]
@SiddharthBahuguna I have checked the website and can confirm that the issue persists; the cards are still not responding to hover actions. Could you please reopen this issue for further review?


https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/153659573/22fb94de-94f9-4a57-9cdc-424131af8e3b

**Comment by SiddharthBahuguna** [comment]
Please try now.

**Comment by SiddharthBahuguna** [comment]
The issue you are currently working on is not a significant task. Please
find a more substantial one so that I can assign it to you.
