### ISSUE TITLE
Feat: Quick links are not working, when the person is not sign up 

### ISSUE THREAD

**Issue by mukund-gpt** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#64]
### Describe the feature

Quick links are not working, when the person is not sign up , they are just opening the opening the default page

hey @SiddharthBahuguna,
can you plz assign this issue to me, i will manage it   

### Add ScreenShots

![Screenshot 2024-05-21 185854](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/142800930/5bd1467e-ac98-4d4c-a94c-21a0daf73cef)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SiddharthBahuguna** [comment]
assigned

**Comment by anurag6569201** [comment]
@mukund-gpt  and @SiddharthBahuguna  those links are disabled  because having not that much content i disabled them thats not an issue its a feature.... @SiddharthBahuguna please close the issue

**Comment by SiddharthBahuguna** [comment]
Ok @anurag6569201

**Comment by mukund-gpt** [comment]
@SiddharthBahuguna but it should be working if an individual wants to  **contact us or see About us** without sign in

**Comment by anurag6569201** [comment]
> @SiddharthBahuguna but it should be working if an individual wants to  **contact us or see About us** without sign in. it is an extra plus point for the website

those are working check the website once

**Comment by anurag6569201** [comment]
> they only work when person is signed in , but about if a person don't want to sign but want to contact us and see about us

I got you that's not issues it's a feature we don't want to let them contact without sign up after getting sign up they can like on mostly on web pages

**Comment by SiddharthBahuguna** [comment]
Thanks for the clarification.I hope @mukund-gpt you got it.
