### ISSUE TITLE
Feat: Implement  Google login 

### ISSUE THREAD

**Issue by Raghavi-22** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#74]
### Describe the feature

Allow users to sign in  using their existing Google accounts.
@SiddharthBahuguna ,kingly assign me this issue
### Add ScreenShots

![Screenshot (390)](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/118007421/cd8b795b-c8ac-44f6-a829-0983b20f94f0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SiddharthBahuguna** [comment]
You can start working on it.

**Comment by Raghavi-22** [comment]
> You can start working on it.
Thanks @SiddharthBahuguna .I will start working on it now

**Comment by thecloudcode** [comment]
Hi, @Raghavi-22 , I have gone through your code base, and have developed a vivid understanding. Kindly, assign me this issue, I would love to work on it.
