### ISSUE TITLE
[BUG]: Contact Form Submit button not responding

### ISSUE THREAD

**Issue by Varsha010101** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#77]
### What's wrong with the existing documentation

In the contact form on clicking on submit button it is not responding and throwing errors. I can also add a details submitted message on clicking submit button. I want to work on this issue and fix the bug in it. Kindly assign it to me and label it under GSSoC @SiddharthBahuguna

### Add ScreenShots

![Screenshot 2024-05-28 105628](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/142898488/24ed95a0-11a7-493d-8869-dc29e990e774)
![Screenshot 2024-05-28 110945](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/142898488/ba3f706d-3a7d-48b6-89cd-ca54a5b122e6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsha010101** [comment]
I want to work on this issue and fix the bug in it. Kindly assign it to me and label it under GSSoC @SiddharthBahuguna

**Comment by SiddharthBahuguna** [comment]
You can start working on it.

**Comment by anurag6569201** [comment]
did you understand the code of backend @Varsha010101

**Comment by SiddharthBahuguna** [comment]
Let her try @anurag6569201
