### ISSUE TITLE
Navbar is not fixed when scroll down

### ISSUE THREAD

**Issue by Shreesanyog** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#78]
### Describe the feature

When we scroll down the page the navbar is not fixed at the top and user have to return to top to go to other section.

![image](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/166977453/7d62f449-fe75-4299-a2fd-48952946fe77)

### Add ScreenShots

![image](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/166977453/38acdd5f-145b-44e3-b62d-acd48796977e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Me-Nitin** [comment]
Assign me i can Fix it

**Comment by SiddharthBahuguna** [comment]
@Shreesanyog task is assigned to you.
