### ISSUE TITLE
Feat: Enhancing User Engagement with Our New Chatbot Feature

### ISSUE THREAD

**Issue by mohangolakoti** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#80]
### Describe the feature

Hello @SiddharthBahuguna,
The chatbot on the news page enhances user engagement by providing instant access to information and guided navigation. Available directly on the web page, it ensures users can get help and interact with the site anytime, making the news experience more interactive and user-friendly.
Please assign me this 

### Add ScreenShots

A bot like this:
![bot-feat](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/116739999/1e29fd02-f1a3-47d3-b817-6368e1625193)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SiddharthBahuguna** [comment]
@mohangolakoti you can start working on it

**Comment by mohangolakoti** [comment]
@SiddharthBahuguna, Please Check the PR #118
