### ISSUE TITLE
My Bookmarks is not working

### ISSUE THREAD

**Issue by samarsajad** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#81]
### Describe the feature

clicking on " my bookmarks"  leads to ano page found

### Add ScreenShots

![image](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/142666229/d5002bdb-c33b-4c09-b4be-16954b067782)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by samarsajad** [comment]
sir please assign this to me @SiddharthBahuguna

**Comment by SiddharthBahuguna** [comment]
@samarsajad You can start working on it.

**Comment by samarsajad** [comment]
> @samarsajad You can start working on it.

Please review my pull request #84

**Comment by SiddharthBahuguna** [comment]
Ok, I'll do it.
