### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by Princegupta101** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#9]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by Techkunjan** [comment]
@SiddharthBahuguna can i also work on this issue

**Comment by Kalyan9064** [comment]
I would like to work on this . Please could you assign me this issue under GSSOC'24

**Comment by SiddharthBahuguna** [comment]
Yes, you can do that.

**Comment by SiddharthBahuguna** [comment]
@Kalyan9064 I have assigned you.Please start working on it

**Comment by officeneerajsaini** [comment]
@SiddharthBahuguna close this pr this issue alredy done . in this repo already have code of conduct file
