### ISSUE TITLE
redesign the signup/signin form

### ISSUE THREAD

**Issue by paulkrishanu4** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#92]
### Describe the feature

want to redesign the signin / signup form, want add hover effects , borders and more attractive features.

### Add ScreenShots

like this:

![Screenshot_31-5-2024_234118_freefrontend com](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/169196836/ef20589d-d503-429d-89fb-a80733e69d95)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SiddharthBahuguna** [comment]
@paulkrishanu4 already created
