### ISSUE TITLE
Feat:Add Scroll to Top button

### ISSUE THREAD

**Issue by zalabhavy** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#95]
### Describe the feature

Add button for automatically scroll to upside.

### Add ScreenShots

![image](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/126322584/ef34c5ee-84b7-45f5-ae4a-1085f64ce1bc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shubham-Zone** [comment]
@SiddharthBahuguna please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development
