### ISSUE TITLE
Homepage looks like Sign in/ Sign up page

### ISSUE THREAD

**Issue by samarsajad** [SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT#97]
### Describe the feature

The homepage without logging in looks like an ordinary sign up page. I suggest displaying news on the homepage even when the user has not logged in. However we will restrict the features like, adding to bookmarks or copying the news and reporting if the user has not logged in.

### Add ScreenShots

![image](https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/142666229/19ac4df1-0032-46c5-857e-cece29f37b77)
Homepage and the Sign in/ Sign up page serve the same purpose

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by samarsajad** [comment]
Please assign this to me @SiddharthBahuguna

**Comment by SiddharthBahuguna** [comment]
@samarsajad You can start working on it.
